### ISSUE TITLE
Auto-generate HTML docs from RAML

### ISSUE THREAD

**Issue by devarshar** [SpeciesFileGroup/taxonworks_api#10]
* [x] setup a structure for housing the input RAML files (check out how others are setting this up)
* [x] setup a structure for housing the build scripts (`/build` ?)
* [ ] build the conversion script (node/webpack? grunt/gulp? - maybe help from José)
* [x] ensure the build script has proper success/failure responses that can be interpretted and used by the travis environment
* [ ] Demonstrate local build server (analagous to `jekyll server`) that listens to raml file changes and does local builds

**Comment by ankitgohel1996** [comment]
For the first point - What does this part imply? "check out how others are setting this up" ?

**Comment by ankitgohel1996** [comment]
Also, for converting the RAML input files to HTML, there seems to be an NPM package:
https://www.npmjs.com/package/raml2html

Perhaps we could look into using that?

**Comment by mjy** [comment]
* raml2html is precisely the converter we planned to use
* "other setting this up" - i.e. what should the directory structure look like.  For a given github repo that is being used to store RAML docments, how are they laying out the directory structure? We know we need to isolate the raml files, the JS build pipeline (Grunt), and the html documents for the github pages (`/doc`).  Should these be nested in '/src', '/lib' etc.  Just looking to see what others do.  There is a big meta repository of RAML documentaiton we found the other day- it's linked somewhere in the comments of the issues- that might provide clues.

**Comment by mjy** [comment]
I should say "Grunt(?)" -> "Gulp", or any number of other build frameworks are possible.  Suggestions welcome.  We do want to think about repo, however, largely being about configuration rather than code, if possible.

**Comment by jlpereira** [comment]
I already played yesterday with raml2html and taxonworks.raml. Works perfect, probably that should be the package we should use to generate the html files. There is a versión adapted to work directly with Gulp, but its an old one and only works with RAML 0.8. Not big deal, just gonna take a little more config

**Comment by mjy** [comment]
So, there is an opportunity here, perhaps, to fork an NPM module and provide improvements to it rather than create our own build module?  Seems like our work, if done well and generalized could be of use to others.

**Comment by mjy** [comment]
@jlpereira If you can submit a pull request on your work so that others can see your code?

**Comment by ankitgohel1996** [comment]
Adding on to our previous discussion @mjy, you were right about the includes being handled by raml2html itself. I modified taxonworks.raml to the following (as a trivial example to see if includes can be handled properly):

```
 /ping:
  get:  
    responses:  
      200:
        body:
          application/json:
            example: !include example.json
/:
  get:
    responses:
      200:
        body:
```
and moved the example to the example.json file:
`{"pong":false}
`

raml2html was able to render the correct HTML - exactly as it was without the !include in the .raml file.

**Comment by jlpereira** [comment]
I like the idea to contribute to make improvements on that packages, however... raml2html 4.x not works anymore with RAML 0.8, only with RAML 1.0. So, we should fork it and work separatly.

I didnt have any code, just used gulp and and with the example provided on gulp-raml2html run it. Didnt work with taxonworks.raml, but it does with the example provided there.

When I tested raml2html with taxonworks.raml running it from the command line works perfect. But obviously, this was just for test, we still needs to get it work with gulp

**Comment by mjy** [comment]
For the record we can target the latest RAML version, i.e. is there a reason to work with 0.8?

**Comment by jlpereira** [comment]
We're already working at the last version. I dont think there are any reason to use 0.8. Last version of raml2html works only with 1.0

**Comment by ankitgohel1996** [comment]
@mjy @jlpereira Update to [#14](https://github.com/SpeciesFileGroup/taxonworks_api/issues/14)
