### ISSUE TITLE
gulp-raml2html works only with RAML 0.8

### ISSUE THREAD

**Issue by ankitgohel1996** [SpeciesFileGroup/taxonworks_api#14]
`gulp-raml2html` hasn't been updated in a while, and it doesn't support RAML 1.0. I looked at this (from the `raml2html` module page):
https://gist.github.com/iki/784ddd5ab33c1e1b726b

However, I couldn't get this to work either - both with 0.8 and 1.0. The files weren't getting parsed correctly, and the output HTML page just had the default theme with API Documentation as the header.

**Comment by mjy** [comment]
Just a thought- does our stub file have enough information in it to properly test the rendering?

**Comment by jlpereira** [comment]
It should, because works with raml2html running from the command line

**Comment by jlpereira** [comment]
Fork gulp-raml2html probably could be the better way to start with this, we could create a new version for RAML 1.0 and it would be a great contribution for the community

**Comment by ankitgohel1996** [comment]
I think I fixed it - I used the source code from `gulp-raml2html` and used it to create a new version which works with RAML 1.0. I've added the new function in the build script itself, if we want we can later test it and send a PR to `gulp-raml2html.`

It's only a couple of changes - updating deprecated functions from older versions of `raml2html`, and changing the parser to look for RAML 1.0 rather than 0.8 at the top of the .raml file.

**Comment by jlpereira** [comment]
Great work @ankitgohel1996 !

I've already forked and made the changes to get it work on RAML 1.0, It wasn't necesarry make to much changes. I have to go now but I will try to make a package tonight so we could use this without put the code on the gruntfile.js like the example you provided on the top.

I need to readapt the example files for RAML 1.0 and test this with mocha before do this.

**Comment by mjy** [comment]
@jlpereira This can be closed, correct?

**Comment by jlpereira** [comment]
Yes, closing
