### ISSUE TITLE
Alphabetize params list

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_api#41]
For each endpoint let's go ahead and set the standard to be an alphabetized list of params.

**Comment by jrflood** [comment]
OK, I was going by a loose rule of order of occurrence in the filters and grouping by related params (like first_ ... last_...).  Does this apply to modifying the ruby code as well?

**Comment by mjy** [comment]
You can alphabetize the corresponding `api_params` in the controller methods, but you have to do it in 2 passes, the arrays have to come out at the end:

```
:a,
:dus,      # not array
az: []      # array
cus: [],  
```

**Comment by mjy** [comment]
Can be closed I assume?

**Comment by jrflood** [comment]
Done
