### ISSUE TITLE
determine if there is a lossless route from RAML to Swagger

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks_api#8]
@devarsh1997 can you research and answer the question, "If I write my API docs in RAML, then can I convert them losslessly to swagger"?

**Comment by devarshar** [comment]
I am not certain about lossless conversion from RAML to Swagger but there are tools like [Apimatic](https://apimatic.io/) that can convert RAML to Swagger (or vice versa)
